apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: memory-leak-demo
  labels:
    app: memory-leak-demo
    app.kubernetes.io/name: memory-leak-demo
spec:
  source:
    type: Git
    git:
      uri: https://github.com/uniqkod/javadumpmngmt.git
      ref: ocp
    contextDir: .
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
      noCache: false
      forcePull: false
  output:
    to:
      kind: ImageStreamTag
      name: memory-leak-demo:latest
  # triggers:
  # - type: ConfigChange
  # - type: ImageChange
  # - type: GitHub
  #   github:
  #     secret: github-webhook-secret
  # - type: Generic
  #   generic:
  #     secret: generic-webhook-secret
  runPolicy: Serial
  successfulBuildsHistoryLimit: 3
  failedBuildsHistoryLimit: 3
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: memory-leak-demo
  labels:
    app: memory-leak-demo
spec:
  lookupPolicy:
    local: false
