apiVersion: v1
kind: Service
metadata:
  name: volume-mount-controller
  namespace: heapdump
  labels:
    app: volume-mount-controller
spec:
  type: ClusterIP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  internalTrafficPolicy: Local
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: volume-mount-controller
